apiVersion: v1
kind: Service
metadata:
  name: nginx-demo-svc
  namespace: argo-nginx       # âœ… namespace add
spec:
  selector:
    app: nginx-demo
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
